name: Build VuePress And Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: npm --v

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: npm run build
